### ISSUE TITLE
checking on sleep study description

### ISSUE THREAD

**Issue by bbolker** [PsyTeachR/psyteachr.github.io#1]
You point out [here](https://psyteachr.github.io/ug3-stats/introducing-linear-mixed-effects-models.html) that the documentation for the `sleepstudy` data in `lme4` is wrong. I've corrected it to:

> The average reaction time per day (in milliseconds) for subjects in a sleep deprivation study.

> Days 0-1 were adaptation and training (T1/T2), day 2 was baseline (B); sleep deprivation started after day 2.

 > These data are from the study described in Belenky et al. (2003), for the most sleep-deprived group (3 hours time-in-bed) and for the first 10 days of the study, up to the recovery period. The original study analyzed speed (1/(reaction time)) and treated day as a categorical rather than a continuous predictor.

Does that look OK? (I did take a look at the paper.)

I don't actually know where Doug Bates got the data from (they don't seem to be associated with the original paper, that I can find), maybe pers. comm. ?  If you don't know I might ask him - if the full data set is available that would be fun to include.

**Comment by dalejbarr** [comment]
Looks good to me. Thanks for taking care of that. I will update the online textbook to reflect the change.

Regarding the data, I am not sure where Doug Bates got it. I don't have a copy and haven't seen it online. It is a really well-chosen dataset for demonstrating the advantages of mixed-effects modeling, so if the full data could be available, I think that would be great. Thanks!

**Comment by dalejbarr** [comment]
[The textbook chapter](https://psyteachr.github.io/ug3-stats/introducing-linear-mixed-effects-models.html) has now been rewritten in preparation for the next release of lme4 with the corrected `sleepstudy` documention. Thanks again!
