### ISSUE TITLE
Dark theme proposal

### ISSUE THREAD

**Issue by celsient** [PsyTeachR/psyteachr.github.io#2]
Hello! I'm a first year student with some sensory problems. I've been having a lot of difficulty reading through the website because the harsh black-on-white gives me a very bad headache; it's simply too bright for me to comfortably look at.

If it's not too much trouble, would you be able to add a toggle-able dark theme? I've been trying to edit the css to my own liking with the Stylus firefox extension but my code-knowledge simply isn't advanced enough to have the page be any more than an awkward mish-mash of `#000000` & `#FFFFFF`.

Thank you very much!

**Comment by dalejbarr** [comment]
Hi there, thanks for letting us know! We are looking into this and will see what we can do about either adding a toggle for dark theme or rendering a dark-themed version of our books.

**Comment by dalejbarr** [comment]
Hi there, someone from the team suggested using a browser extension such as the [Firefox dark mode extension](https://addons.mozilla.org/en-US/firefox/addon/dark-mode-webextension/). Please re-open this issue if you find things that cannot be resolved with a browser add-on. Hope this helps!

**Comment by celsient** [comment]
Hi from the future, I just wanted to thank you and the rest of the team for this suggestion! I hadn't considered dark theme extensions before, but using one over the past year has completely changed my life :D No more headaches from eye-searing pages!!! Thank you!

**Comment by dalejbarr** [comment]
That is lovely to hear, thank you for following up! Suggestion for the plug in was from @HelenaPaterson
